/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.clock;

import java.awt.event.ActionListener;

/**
 *
 * @author fermigo
 */
public class ClockConfigurationDialog extends javax.swing.JDialog {

    /**
     * Creates new form ClockConfigurationJDialog
     */
    public ClockConfigurationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeButtonGroup = new javax.swing.ButtonGroup();
        messageLabel = new javax.swing.JLabel();
        hourLabel = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        clockModeLabel = new javax.swing.JLabel();
        m24hRadioButton = new javax.swing.JRadioButton();
        m12hRadioButton = new javax.swing.JRadioButton();
        hourSpinner = new javax.swing.JSpinner();
        minutesSpinner = new javax.swing.JSpinner();
        setButton = new javax.swing.JButton();
        enableDisableAlarmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        messageLabel.setText("Message:");

        hourLabel.setText("Alert time:");

        clockModeLabel.setText("Clock mode:");

        modeButtonGroup.add(m24hRadioButton);
        m24hRadioButton.setText("24H");
        m24hRadioButton.setActionCommand("24h");

        modeButtonGroup.add(m12hRadioButton);
        m12hRadioButton.setText("12H");
        m12hRadioButton.setActionCommand("12h");

        hourSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        minutesSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        setButton.setText("Set clock");

        enableDisableAlarmButton.setText("Enable alarm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clockModeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(m24hRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(m12hRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hourLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addGap(18, 18, 18)
                        .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(setButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enableDisableAlarmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clockModeLabel)
                    .addComponent(m24hRadioButton)
                    .addComponent(m12hRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourLabel)
                    .addComponent(hourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enableDisableAlarmButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getMode() {
        return modeButtonGroup.getSelection().getActionCommand();
    }

    public void setMode(boolean mode24) {
        if (mode24) {
            this.m24hRadioButton.setSelected(true);
        } else {
            this.m12hRadioButton.setSelected(true);
        }
    }

    public String getMessage() {
        return this.messageTextField.getText();
    }

    public void setMessage(String message) {
        this.messageTextField.setText(message);
    }

    public int getMinutes() {
        return (int) this.minutesSpinner.getValue();
    }

    public void setMinutes(int minutes) {
        this.minutesSpinner.setValue(minutes);
    }

    public void setHour(int hour) {
        this.hourSpinner.setValue(hour);
    }

    public int getHour() {
        return (int) this.hourSpinner.getValue();
    }

    public void enableDisableAlarm(boolean enable) {
        if (enable) {
            this.enableDisableAlarmButton.setText("Disable Alarm");
        } else {
            this.enableDisableAlarmButton.setText("Enable Alarm");
        }
    }

    public void addSetButtonActionListerner(ActionListener listener) {
        this.setButton.addActionListener(listener);
    }

    public void addEnableDisableAlarmButtonActionListerner(ActionListener listener) {
        this.enableDisableAlarmButton.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockModeLabel;
    private javax.swing.JButton enableDisableAlarmButton;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JSpinner hourSpinner;
    private javax.swing.JRadioButton m12hRadioButton;
    private javax.swing.JRadioButton m24hRadioButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JSpinner minutesSpinner;
    private javax.swing.ButtonGroup modeButtonGroup;
    private javax.swing.JButton setButton;
    // End of variables declaration//GEN-END:variables
}
