/*#1
SELECT * FROM emp;
#2
SELECT * FROM deptno;
#3
SELECT * FROM emp WHERE PUESTO = "CONTABLE";
#4
SELECT * FROM emp WHERE PUESTO = "CONTABLE" ORDER BY NOEMP;
#5
SELECT * FROM emp WHERE PUESTO = "CONTABLE" ORDER BY NOEMP DESC;
#6
SELECT NOEMP AS 'NOMBRE', SAL AS 'SALARIO' FROM emp;
#7
SELECT NOMDEP AS 'NOMBRE_DEPTO' FROM deptno;
#8
SELECT NOMDEP AS 'NOMBRE_DEPTO' FROM deptno ORDER BY LOCALIDAD;
#9
SELECT NOEMP, PUESTO FROM emp ORDER BY SAL DESC;
#10
SELECT NOEMP, PUESTO FROM emp ORDER BY PUESTO, SAL;
*/
#11
SELECT SAL, COMISION FROM emp WHERE NUMDEP = 3;
#12
SELECT SAL, COMISION FROM emp WHERE NUMDEP = 3 ORDER BY COMISION;
#13
SELECT DISTINCT(COMISION) FROM emp;
#14