
package view.establishmentDetails;

import java.awt.Button;
import java.awt.event.ActionListener;


public class EstablishmentDetailsDialog extends javax.swing.JDialog {

    
    public EstablishmentDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void addCancelButtonActionListener(ActionListener listener) {
        this.cancelButton.addActionListener(listener);
    }
    
    public void addEditButtonActionListener(ActionListener listener) {
        this.editButton.addActionListener(listener);
    }
    
    public void addSaveButtonActionListener(ActionListener listener) {
        this.saveButton.addActionListener(listener);
    }
    
    public String getNameTextField() {
        return this.nameTextField.getText();
    }
    
    public String getAddressTextField() {
        return this.addressTextField.getText();
    }
    
    public String getPhoneTextField() {
        return this.phoneTextField.getText();
    }
    
    public int getEmployeesSpinnerValue() {
        return (Integer) this.employeesSpinner.getValue();
    }
   
    
    public void setNameTextField(String name) {
        this.nameTextField.setText(name);
    }
    
    public void setAddressTextField(String address) {
        this.addressTextField.setText(address);
    }
    
    public void setPhoneTextField(String phoneNumber) {
        this.phoneTextField.setText(phoneNumber);
    }
    
    public void setNumberOfEmployees(int numberOfEmployees) {
        this.employeesSpinner.setValue((Integer) numberOfEmployees);
    }
    
    public void setSaveButtonEnabled(boolean status) {
        this.saveButton.setEnabled(status);
    }
    
    public void setEditButtonEnabled(boolean status) {
        this.editButton.setEnabled(status);
    }
    
    public void setNameTextFieldEditable(boolean status) {
        this.nameTextField.setEditable(status);
    }
    
    public void setAddressTextFieldEditable(boolean status) {
        this.addressTextField.setEditable(status);
    }
    
    public void setPhoneTextFieldEditable(boolean status) {
        this.phoneTextField.setEditable(status);
    }
    
    public void setEmployeesSpinnerEnabled(boolean status) {
        this.employeesSpinner.setEnabled(status);
    }
    
    public void setCancelButtonEnabled(boolean status) {
        this.cancelButton.setEnabled(status);
    }
    
    public boolean isEditButtonEnabled() {
        return editButton.isEnabled();
    }
    
    public boolean isSaveButtonEnabled() {
        return saveButton.isEnabled();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        establishmentDetailsLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        employeesLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        employeesSpinner = new javax.swing.JSpinner();
        underlineLabel = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        establishmentDetailsLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        establishmentDetailsLabel.setText("Establishment details");

        nameLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        nameLabel.setText("Name:");

        addressLabel.setText("Address:");

        phoneLabel.setText("Phone:");

        employeesLabel.setText("Nº of employees:");

        editButton.setText("Edit");

        saveButton.setText("Save");

        cancelButton.setText("Cancel");

        underlineLabel.setFont(new java.awt.Font("Liberation Sans", 0, 13)); // NOI18N
        underlineLabel.setText("_______________________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(establishmentDetailsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressLabel)
                                    .addComponent(nameLabel)
                                    .addComponent(phoneLabel)
                                    .addComponent(employeesLabel)))
                            .addComponent(saveButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(addressTextField)
                                    .addComponent(phoneTextField)
                                    .addComponent(employeesSpinner))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(editButton)
                                .addGap(56, 56, 56)
                                .addComponent(cancelButton)
                                .addGap(37, 37, 37))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(underlineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(establishmentDetailsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeesLabel)
                    .addComponent(employeesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel employeesLabel;
    private javax.swing.JSpinner employeesSpinner;
    private javax.swing.JLabel establishmentDetailsLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel underlineLabel;
    // End of variables declaration//GEN-END:variables
}
